services:
  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:3241@postgres:5432/todo-app # Need to use DB_URL from neon db
    depends_on:
      - postgres

  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL:postgresql://postgres:3241@postgres:5432/todo-app
        # you may have to change DB_URL to DATABASE_URL
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:3241@postgres:5432/todo-app
    depends_on:
      - postgres

  ws:
    build:
      context: ./
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:3241@postgres:5432/todo-app
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=3241
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volume: postgres_data
